### ISSUE TITLE
Reflective error

### ISSUE THREAD

**Issue by heshriti** [CharlesSkelton/studio#27]
Hi Charles,

I have this error when I try to open studio in mac. It seems to work despite the warnings.
Still, any way these issues can be fixed?

thanks.

-----

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by studio.utils.OSXAdapter (file:studio.jar) to constructor com.apple.eawt.Application()
WARNING: Please consider reporting this to the maintainers of studio.utils.OSXAdapter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
This version of Mac OS X does not support the Apple EAWT.  ApplicationEvent handling has been disabled (java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener)
This version of Mac OS X does not support the Apple EAWT.  ApplicationEvent handling has been disabled (java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener)
OSXAdapter could not access the About Menu
java.lang.NoSuchMethodException: com.apple.eawt.Application.setEnabledAboutMenu(boolean)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2633)
	at studio.utils.OSXAdapter.setAboutHandler(Unknown Source)
	at studio.ui.StudioPanel.registerForMacOSXEvents(Unknown Source)
	at studio.ui.StudioPanel.<init>(Unknown Source)
	at studio.ui.StudioPanel.init(Unknown Source)
	at studio.core.Studio$1.run(Unknown Source)

**Comment by dzmipt** [comment]
I suspect you are running on Java 9 or later. It looks they replaced com.applet.eawt.* with something different in Java 9 (more comments see at https://stackoverflow.com/questions/13978471/com-apple-eawt-what-exactly-i-should-install).
I have Java 8 on MacOS. And it works for me.

**Comment by heshriti** [comment]
From the java control panel, I have Java 8 too. v 291.

from command line- I have java 15

**Comment by heshriti** [comment]
Hi,

anyway to fix these errors?

**Comment by dzmipt** [comment]
@heshriti, I've just added support for native MacOs menu for Java 9+ in my fork: https://github.com/dzmipt/kdbStudio. Any feedback is welcomed.
